USE [master]
GO

/****** Object:  Database [DatabaseHectorMite]    Script Date: 27/05/2023 12:58:41 ******/
CREATE DATABASE [DatabaseHectorMite]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DatabaseHectorMite', FILENAME = N'C:\DATA\DatabaseHectorMite.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DatabaseHectorMite_log', FILENAME = N'C:\DATA\DatabaseHectorMite_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DatabaseHectorMite].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DatabaseHectorMite] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DatabaseHectorMite] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DatabaseHectorMite] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DatabaseHectorMite] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DatabaseHectorMite] SET ARITHABORT OFF 
GO

ALTER DATABASE [DatabaseHectorMite] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DatabaseHectorMite] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DatabaseHectorMite] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DatabaseHectorMite] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DatabaseHectorMite] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DatabaseHectorMite] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DatabaseHectorMite] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DatabaseHectorMite] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DatabaseHectorMite] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DatabaseHectorMite] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DatabaseHectorMite] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DatabaseHectorMite] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DatabaseHectorMite] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DatabaseHectorMite] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DatabaseHectorMite] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DatabaseHectorMite] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DatabaseHectorMite] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DatabaseHectorMite] SET RECOVERY FULL 
GO

ALTER DATABASE [DatabaseHectorMite] SET  MULTI_USER 
GO

ALTER DATABASE [DatabaseHectorMite] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DatabaseHectorMite] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DatabaseHectorMite] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DatabaseHectorMite] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DatabaseHectorMite] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DatabaseHectorMite] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [DatabaseHectorMite] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DatabaseHectorMite] SET  READ_WRITE 
GO


